name: 'Hello World'
description: 'Hello world from github actions'
inputs:
  text:
    description: github repository name
    required: true
    default: ${{ github.repository }}

runs:
  using: 'docker'
  image: 'Dockerfile'
