# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: package-lock.json
    - uses: snow-actions/tweet@v1.1.0
      env:
        CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
        ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      with:
        status: "Hi, this is a test!"
