name: tweet bot 4

on:
  push:
    branches: [ main ]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: tweet oauth
      run: |
        curl -X POST -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" \
        -H "Authorization: Basic QUFBQUFBQUFBQUFBQUFBQUFBQUFBQzU1c0FFQUFBQUFydGVncllWbGtmUjJPTGtDbnZDNlJFVFdrZmslM0RvbFpNTkZ0S3RDeFI2NmtEYkZuRmpFaDBHYmNmRm1Hcm13VjdBWE9ndDBVZDRPaGEwaQ==" \
        -d "grant_type=client_credentials" https://api.twitter.com/oauth2/toke
    - name: Tweet on Push
      env:
        TWITTER_BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      run: |
        curl -X POST 'https://api.twitter.com/2/tweets' \
        --header "Authorization: Bearer AAAAAAAAAAAAAAAAAAAAAC55sAEAAAAArtegrYVlkfR2OLkCnvC6RETWkfk%3DolZMNFtKtCxR66kDbFnFjEh0GbcfFmGrmwV7AXOgt0Ud4Oha0i" \
        -H 'Content-Type: application/json' \
        -d '{"test": "hello World!"}'

