name: tweet bot 4(curl)

on:
  push:
    branches: [ main ]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Tweet on Push
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |
        curl -X POST \
             --url 'https://api.twitter.com/1.1/statuses/update.json' \
        --header "Authorization: OAuth oauth_consumer_key=${TWITTER_CONSUMER_KEY},oauth_consumer_secret=${TWITTER_CONSUMER_SECRET},oauth_token=${TWITTER_ACCESS_TOKEN},oauth_token_secret=${TWITTER_ACCESS_TOKEN_SECRET},oauth_signature_method='HMAC-SHA1',oauth_version='1.0'" \
        -H 'Content-Type: application/json' \
        -d '{"status": "hello World!"}'

