name: tweet bot

on:
  push:
    branches: [ main ]

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: package-lock.json
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "20"
        cache: npm
    - run: npm install
    - uses: twitter-together/action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        TWITTER_ACCESS_TKOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}


